# Generated by Django 4.2.4 on 2023-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pay_id', models.CharField(max_length=100)),
                ('latest_pay', models.DateField()),
            ],
        ),
    ]
