# Generated by Django 4.2.4 on 2023-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_signalsmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodal',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
