# Generated by Django 4.2.4 on 2023-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_paymentmodal_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodal',
            name='email',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
